
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package aux_tools.sintactico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Mul = 73;
  public static final int display = 11;
  public static final int verde = 90;
  public static final int Menor = 75;
  public static final int facil_sino = 18;
  public static final int facil_mientras = 14;
  public static final int incrementar = 57;
  public static final int motor = 36;
  public static final int fin_programa = 20;
  public static final int azul = 91;
  public static final int motor_electrico = 37;
  public static final int Div = 74;
  public static final int DosPuntos = 62;
  public static final int Resta = 72;
  public static final int mientras = 33;
  public static final int estado = 88;
  public static final int detener = 80;
  public static final int sino = 45;
  public static final int fin_bloque = 49;
  public static final int decimal = 50;
  public static final int arreglo = 92;
  public static final int Suma = 71;
  public static final int caso = 7;
  public static final int veces = 47;
  public static final int mostrar = 35;
  public static final int inicio_var = 28;
  public static final int ERROR = 81;
  public static final int incluir = 26;
  public static final int decrementar = 58;
  public static final int grados = 23;
  public static final int y = 54;
  public static final int definir = 9;
  public static final int PUNTO_COMA = 61;
  public static final int inicio_bloque = 6;
  public static final int girar = 22;
  public static final int o = 56;
  public static final int COMA = 83;
  public static final int seg = 42;
  public static final int motor_paso = 38;
  public static final int facil_bloque = 12;
  public static final int Lla_c = 66;
  public static final int hr = 25;
  public static final int Lla_a = 65;
  public static final int avanzar = 86;
  public static final int prender = 39;
  public static final int facil_si = 17;
  public static final int no = 55;
  public static final int inicio_programa = 27;
  public static final int facil_hacer_mientras = 13;
  public static final int retroceder = 87;
  public static final int facil_repetir = 15;
  public static final int derecha = 10;
  public static final int texto = 52;
  public static final int Menor_i = 79;
  public static final int Mayor = 76;
  public static final int facil_selector = 16;
  public static final int Texto = 4;
  public static final int EOF = 0;
  public static final int PUNTO = 82;
  public static final int repetir = 40;
  public static final int falso = 19;
  public static final int logico = 53;
  public static final int Numero = 2;
  public static final int led = 31;
  public static final int rojo = 89;
  public static final int arregloBi = 93;
  public static final int verdadero = 48;
  public static final int Tiempo = 60;
  public static final int error = 1;
  public static final int Cor_c = 68;
  public static final int Cor_a = 67;
  public static final int tiempo = 46;
  public static final int Diferente = 77;
  public static final int si = 44;
  public static final int entero = 51;
  public static final int selector = 43;
  public static final int visualizar = 84;
  public static final int izquierda = 30;
  public static final int Asignacion_s = 70;
  public static final int salir = 41;
  public static final int como = 8;
  public static final int hacer = 24;
  public static final int Identificador = 59;
  public static final int para = 85;
  public static final int fin_var = 21;
  public static final int Mayor_i = 78;
  public static final int Par_c = 64;
  public static final int Igual = 69;
  public static final int Par_a = 63;
  public static final int min = 34;
  public static final int apagar = 5;
  public static final int Decimal = 3;
  public static final int ledRGB = 32;
  public static final int intensidad = 29;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Numero",
  "Decimal",
  "Texto",
  "apagar",
  "inicio_bloque",
  "caso",
  "como",
  "definir",
  "derecha",
  "display",
  "facil_bloque",
  "facil_hacer_mientras",
  "facil_mientras",
  "facil_repetir",
  "facil_selector",
  "facil_si",
  "facil_sino",
  "falso",
  "fin_programa",
  "fin_var",
  "girar",
  "grados",
  "hacer",
  "hr",
  "incluir",
  "inicio_programa",
  "inicio_var",
  "intensidad",
  "izquierda",
  "led",
  "ledRGB",
  "mientras",
  "min",
  "mostrar",
  "motor",
  "motor_electrico",
  "motor_paso",
  "prender",
  "repetir",
  "salir",
  "seg",
  "selector",
  "si",
  "sino",
  "tiempo",
  "veces",
  "verdadero",
  "fin_bloque",
  "decimal",
  "entero",
  "texto",
  "logico",
  "y",
  "no",
  "o",
  "incrementar",
  "decrementar",
  "Identificador",
  "Tiempo",
  "PUNTO_COMA",
  "DosPuntos",
  "Par_a",
  "Par_c",
  "Lla_a",
  "Lla_c",
  "Cor_a",
  "Cor_c",
  "Igual",
  "Asignacion_s",
  "Suma",
  "Resta",
  "Mul",
  "Div",
  "Menor",
  "Mayor",
  "Diferente",
  "Mayor_i",
  "Menor_i",
  "detener",
  "ERROR",
  "PUNTO",
  "COMA",
  "visualizar",
  "para",
  "avanzar",
  "retroceder",
  "estado",
  "rojo",
  "verde",
  "azul",
  "arreglo",
  "arregloBi"
  };
}

